
user:
    resource: "@userBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
tfg_admin:
    resource: "@TFGAdminBundle/Resources/config/routing.yml"
    prefix:   /
