<?php

namespace userBundle\Entity;

/**
 * ForoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForoRepository extends \Doctrine\ORM\EntityRepository
{
}
