user_user:
    resource: "@userBundle/Resources/config/routes/user.yml"
    prefix:   /user

partida_partida:
    resource: "@userBundle/Resources/config/routes/partida.yml"
    prefix:   /partida

foro_foro:
    resource: "@userBundle/Resources/config/routes/foro.yml"
    prefix:   /foro

comment:comment:
    resource: "@userBundle/Resources/config/routes/comment.yml"
    prefix:   /comment

# Autentication
user_homepage:
    path:     /home
    defaults: { _controller: userBundle:User:home }

user_login:
    path:     /login
    defaults: { _controller: userBundle:Security:login }

user_login_check:
    path:     /login_check
    defaults: { _controller: userBundle:Security:loginCheck }

user_logout:
    path:     /logout

#registros de nuevos jugadores
user_add:
  path: /add
  defaults: { _controller: userBundle:User:add }
  
# planetas
user_planets:
    path:     /planets
    defaults: { _controller: userBundle:User:planets }

# enemys
user_enemies:
    path:     /enemies
    defaults: { _controller: userBundle:User:enemies }

# anonimous
user_homeForStrangers:
    path:     /home2
    defaults: { _controller: userBundle:User:home }