user_homepage:
    path:     /hello/{name}
    defaults: { _controller: userBundle:Default:index }

user_index:
  path: /index
  defaults: { _controller: userBundle:User:index }

user_add_admin:
  path: /add/admin
  defaults: { _controller: userBundle:User:addAdmin }

user_create:
  path: /create
  defaults: { _controller: userBundle:User:create }
  methods: POST

user_create_admin:
  path: /createAdmin
  defaults: { _controller: userBundle:User:createAdmin }
  methods: POST

user_edit:
  path: /edit/{id}
  defaults: { _controller: userBundle:User:edit }

user_update:
  path:     /update/{id}
  defaults: { _controller: userBundle:User:update }
  methods: [POST, PUT]

user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: userBundle:User:delete }
    methods: [POST, DELETE]

user_view:
  path: /view/{id}
  defaults: { _controller: userBundle:User:view }

user_delete:
  path: /delete/{id}
  defaults: { _controller: userBundle:User:delete }
  methods: [POST, DELETE]

user_redirect_add_admin:
    path: /create
    defaults:
        _controller: userBundle:User:add
        path: /user/add/admin
        permanent: true

user_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: userBundle:User:edit
        path: /user/edit/{id}
        permanent: true